#配置文件启用
profile:
    active: ${ACTIVE:dev} # 使用的环境(dev 开发;test 测试环境;prod 生产环境)
logger:
    level: ${LOG_LEVEL:info} # 日志级别：debug,info,warning,error,crit
    prefix: ${LOG_PREFIX:} #日志文件前缀
    parent: ${LOG_PARENT:} #日志父级目录
email:
    alarm: ${EMAIL_ALARM:true}
    code: ${EMAIL_CODE:DEMO-CODE-XXXXX} #数据库发送配置的编码
    subject: ${EMAIL_SUBJECT:邮件主题}
    kafka_topic:  ${KAFKA_TOPIC:app-email-alarm}
    kafka_servers: ${KAFKA_SERVERS:hadoopdev01:19092,hadoopdev02:19092,hadoopdev03:19092}

#数据库配置
datasource:
    mysql:
        host: ${MYSQL_HOST:127.0.0.1}
        port: ${MYSQL_PORT:3306}
        user: ${MYSQL_USER:root}
        passwd: ${MYSQL_PASSWD:root}
        db: ${MYSQL_DB:huidian}
        charset: ${MYSQL_CHARSET:utf8}



